app = "chario"
kill_signal = "SIGTERM"
kill_timeout = 30
[build]
  image = "ghcr.io/${{ github.repository }}:${{ github.sha }}"
[env]
  PORT = "3000"
[deploy]
  strategy = "rolling"
  release_command = "npx prisma migrate deploy"
