name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: chario
          POSTGRES_PASSWORD: chario
          POSTGRES_DB: chario_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U chario"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx markdown-lint docs/**/*.md
      - run: npx prisma migrate deploy
        env:
          DATABASE_URL: 'postgresql://chario:chario@localhost:5432/chario_test'
      - run: npm run test:coverage
        env:
          DATABASE_URL: 'postgresql://chario:chario@localhost:5432/chario_test'
      - run: bash .github/scripts/coverage-gate.sh
      - uses: github/codeql-action/analyze@v3
      - uses: trufflesecurity/trufflehog@v3.89.1
        with:
          path: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
