name: Secret Scan

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for hard-coded secrets
        run: |
          if git grep -nEI "(AKIA[0-9A-Z]{16}|['\"]?(secret|token|password|api_key)['\"]?\s*[:=]\s*['\"][A-Za-z0-9]{16,}['\"])" -- "."; then
            echo "Potential secret detected" >&2
            exit 1
          else
            echo "No secrets found"
          fi
